version: "3.7"

services:
  web:
    image: covid-hackathon-web:latest
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - db
      - ui
  ui:
    image: covid-hackathon-ui:latest
    ports:
      - 80:80
    environment:
      - "API_URL=http://web:5000"
  db:
    image: covid-hackathon-db:latest
    ports:
      - 5003:5432
    # volumes: # ???
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=help_directory
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=docker
    restart: always
    networks:
      - default
volumes:
  postgres_data:
